#!/bin/bash

command -v xsel >/dev/null || exit 1
command -v wc >/dev/null || exit 1
command -v kdialog >/dev/null || exit 1

case "$1" in
    "-p"|"-b"|"-s"|"")
        :
        ;;
    *)
        exit 1
        ;;
esac

xsel_cmd="xsel -o $1"
kdialog --title "Cliplen" --msgbox "The length of '$xsel_cmd' is $(eval $xsel_cmd | wc -c)"
