#!/bin/bash

export HISTSIZE=100000
export HISTCONTROL=ignoreboth
export HISTTIMEFORMAT="%d/%m/%y %T "
export TERM=xterm-256color

export EDITOR=emacsclient

COMP_WORDBREAKS="${COMP_WORDBREAKS//:}"
COMP_WORDBREAKS="${COMP_WORDBREAKS//@}"

stty -ixon
set +H
