#!/bin/bash

_svc() {
    local act="$1"
    shift
    while [ $# -gt 0 ]; do
        sudo "/etc/init.d/$1" $act
        shift
    done
}

rsv() {
    _svc restart "$@"
}
sv() {
    _svc start "$@"
}
ssv() {
    _svc stop "$@"
}
stsv() {
    _svc status "$@"
}
rlsv() {
    _svc reload "$@"
}


_services_complete() {
    local cur=${COMP_WORDS[COMP_CWORD]}
    COMPREPLY=( $(compgen -W "$(ls /etc/init.d | grep -Ev '(~$|^#.*#$)')" -- $cur) )
}

_runlevels_complete() {
    local cur=${COMP_WORDS[COMP_CWORD]}
    local rcs=
    local r
    for r in `ls /etc/runlevels`; do
        [ -d /etc/runlevels/$r ] && rcs+="$r "
    done
    COMPREPLY=( $(compgen -W "$rcs" -- $cur) )
}

complete -F _services_complete rsv
complete -F _services_complete sv
complete -F _services_complete ssv
complete -F _services_complete stsv
complete -F _services_complete rlsv

complete -F _runlevels_complete openrc
